apiVersion: v1
kind: Service
metadata:
  name: svc-product-api
spec:
  selector:
    app: product-api
  ports:
    - protocol: 'TCP'
      port: 9902         # Port on which you have to expose the service
      targetPort: 9902   # Port of the container as specified in application
  type: LoadBalancer